version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/src:/app/src
      - ./backend/types:/app/types   
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/types:/app/types
    environment:
      NODE_ENV: production

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/redirection-panel/browser:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redirections
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d/